### PR TITLE
Clamp document_frequency in bm25 score before_each().

### LINKED ISSUE #24: panic: attempt to subtract with overflow
```
thread 'main' panicked at /home/alice/.cargo/registry/src/index.crates.io-6f17d22bba15001f/probly-search-2.0.0/src/score/default/bm25.rs:56:24:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```toml
probly-search = "2.0.0"
```

```rust
use probly_search::{score::bm25, Index};
use std::borrow::Cow;

struct Doc {
    id: usize,
    content: String,
}

// A white space tokenizer
fn tokenizer(s: &str) -> Vec<Cow<str>> {
    s.split(' ').map(Cow::from).collect::<Vec<_>>()
}

fn content_extract(d: &Doc) -> Vec<&str> {
    vec![&d.content]
}

fn main() {
    let mut index = Index::<usize>::new(1);

    let contents = std::fs::read_to_string("tmp/data.json").unwrap();
    let data: Vec<String> = serde_json::from_str(&contents).unwrap();
    for (id, content) in data.iter().enumerate() {
        let doc = Doc {
            id,
            content: content.to_string(),
        };
        index.add_document(&[content_extract], tokenizer, doc.id, &doc);
    }

    let result = index.query(
        &" What did the author do growing up?",
        &mut bm25::new(),
        tokenizer,
        &[1.],
    );
    println!("{result:?}");
}

```

[tmp/data.json](https://github.com/user-attachments/files/15906384/data.json) paul_graham_essay.txt RecursiveCharacterTextSplitter(chunk_size:1500, chuck_overlap:100)

### PR DESCRIPTION
**Pull request by tmpfs**
Closes #24.

### CODE REVIEW

**Comment by marcus-pousette** [comment]
Looks good! hough it would be nice to have a test to make sure this issue does not appear again later :)

**Comment by marcus-pousette** [comment]
I have no problem merging this how it is, but want you to have the opportunity to add test if you like!

**Comment by tmpfs** [comment]
Good call @marcus-pousette , I've added a simple test spec which triggers the code path and ensures no panic!

LGTM 🙏

**Comment by marcus-pousette** [comment]
awesomee!

**Pull request merged**
